### ISSUE TITLE
如何通过registerUI来添加自定义按钮

### ISSUE THREAD

**Issue by Link-Fight** [notadd/neditor#77]
首选，已使用百度的ueditor通过提供的registerUI来添加自定义的按钮。
```js
window.UE.registerUI('Button', function (editor, uiName) {
    return new window.UE.ui.Button({
          // do the jod
     })
})
```
[ueditor上的相关文档](http://fex.baidu.com/ueditor/#dev-developer)

而到了neditor,方法失败且报错。
通过看到源代码，同是提供的`registerUI(uiName,fn,index,editorId)`方法，
- 在`ueditor`中注册的`uiName`是用`UE._customizeUI`来放置的，然后遍历这个对象来生成外部定制的UI.
- 在`neditor`中注册的`uiName`使用`baidu.editor.ui`来放置，而里面会有内部内置的UI，例如`baidu.editor.ui.ColorPicker`,`baidu.editor.ui.Button`,`baidu.editor.ui.Toolbar`等等内部的UI,而按照我之前的写法，`baidu.editor.ui.Button`会被`window.UE.registerUI('Button',fn)`给重置了，将导致内部错误。
- 从源代码中看来，neditor是错误实现了`registerUI`方法，应该采用`ueditor`的实现方式。

**Comment by zuohuadong** [comment]
目前由于图标问题，自定义会比较困难。
下个版本会解决，如果想一起开发的话，欢迎加入Q群：257753500

**Comment by zuohuadong** [comment]
已经在此做了说明： https://github.com/notadd/neditor/issues/81

**Comment by Link-Fight** [comment]
好的！明白。

- 我现在是直接修改了源代码，把原来的实现搬运过来，而图标的问题，
- 我是通过样式覆盖来解决的。
- 在通过`new window.UE.ui.Button`来注册按钮时候，有个参数`name`。通过观察，而在生成自定义按钮的时候，其按钮的`classlist`中会有个`edui-for-${name}的属性'，所以通过指定样式就可以定制到需要的图标了。
```css
.edui-for-addProduct .edui-notadd {
  background-image: url("../assets/addProduct.svg") !important;
  background-size: 80%;
  background-position: center;
  background-repeat: no-repeat;
}
```

![image](https://user-images.githubusercontent.com/9206393/49224060-66c0b600-f41b-11e8-8d54-ed9932279398.png)
